//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ImageImporter {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Configuration.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("configuration", Namespace="http://tempuri.org/Configuration.xsd", IsNullable=false)]
    public partial class Configuration {
        
        private FileTypes fileTypesField;
        
        private string patternField;
        
        private string destinationField;
        
        /// <remarks/>
        public FileTypes FileTypes {
            get {
                return this.fileTypesField;
            }
            set {
                this.fileTypesField = value;
            }
        }
        
        /// <remarks/>
        public string Pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
        
        /// <remarks/>
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Configuration.xsd")]
    public partial class FileTypes {
        
        private string[] rawFileTypesField;
        
        private string[] nonRawFileTypesField;
        
        private string[] videoFileTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FileType", IsNullable=false)]
        public string[] RawFileTypes {
            get {
                return this.rawFileTypesField;
            }
            set {
                this.rawFileTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FileType", IsNullable=false)]
        public string[] NonRawFileTypes {
            get {
                return this.nonRawFileTypesField;
            }
            set {
                this.nonRawFileTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FileType", IsNullable=false)]
        public string[] VideoFileTypes {
            get {
                return this.videoFileTypesField;
            }
            set {
                this.videoFileTypesField = value;
            }
        }
    }
}
