trigger:
    branches:
        include:
            - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'b33f3216-3cef-4872-a4b5-f8934534ed42'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solution)'